[package]
name = "d2-tools"
version = "0.0.0"
description = "d2-tools desktop"
edition = "2021"

[lib]
name = "d2_tools_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
